//
//  main.cpp
//  Lab1
//
//  Created by Jeremy Sommers on 8/25/17.
//  Copyright © 2017 Jeremy Sommers. All rights reserved.
//

#include <iostream>
#include <string>

using namespace std;
void charCount(string text) {
    int a = 0;
    int c = 0;
    int g = 0;
    int t = 0;
    
    for (int i = 0; i < text.length(); i++) {
        if (text.at(i) == 'A')
            a+=1;
        if (text.at(i) == 'C')
            c+=1;
        if (text.at(i) == 'G')
            g+=1;
        if (text.at(i) == 'T')
            t+=1;
    }
    cout << a << endl;
    cout << c << endl;
    cout << g << endl;
    cout << t << endl;
}

int main(int argc, const char * argv[]) {
    // insert code here...
    charCount("AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC");
    charCount("AACGGCGGGAAGGCGGGACCGGAAGCGGACAGGACTGGGAGAGGCACAACCCGGGGCGCAGTTGATCACCACCCCTTAAAATGCGCGACAAGGAGAGTAACCCGACGTAGATCTGTGTTTCGGTGACAACCTTAGGGATGTAGACGAGGATCGCAGGACAAATAAGATAGAGTCTGATTCGCGTCAGCAAGTTCCAAATCGTTCCACCCGCCTATGAACTCCCCTGAGACTTTCTGCCGAACAGAGTTGCTCCATCATTGAACTTGCTGTGACATCTGCCTATTCAGAGGAAAAGGTGCCGCCAGTCGGGAGCAGGTCCAACCTCATAATCATGGGATATGGAATTCACAGAGCGTGGAGGGACTATTATTCTCATAGCGTAGACTGCTTTCACTGCCACTGCCCACCCCTTTAGTACATAATGCTAAGCATTACTCGACTGCCAGAACAGACAACAAGGAATCCTTGCCCTCCATAAGCCCTGTTCGGCGTCCTTGATACACAACGGTGTGGGGTCCCGCTATGTTGCAAGTCACAGTATGGTGGCTGATCCAAATCGCGCTCTAAGGCACCCTCGCGAAATTTGTACGTCTATTTAGCTGCGGGACGGGGCGCGAAATACACATCTAAGAACCACGCCTGCTAATGTCTAACATAACTAACTAATCCATGCGTGGCACTCAACTGGGGGCTGACTGAGCCATAACATCCTGCGTGAAGATTCTTGCGCTAGCCCAGGGGCTCATTAGAGTGAAGGTCCTGCACCGCAGAGAGTAGAGCGATGCTCAGACACGCGCCCAACACCTGGGCCAAAACAAATTAGACCCGCTATCCCCTCCATGAAGCAAGCAAAATGGCTAATGACCATAGTAGTGCCCGTCATGAGTCTGCGACGAGTGACAGGACCCGGGCGTGGGAATGTACGA");
    return 0;
}