//
//  main.cpp
//  GlobalAlignment
//
//  Created by Jeremy Sommers on 10/20/17.
//  Copyright © 2017 Jeremy Sommers. All rights reserved.
//

#include <iostream>
#include <string>
#include <sstream>
using namespace std;
string charToString(char c) {
    stringstream stream;
    string value;
    stream << c;
    stream >> value;
    return value;
}
void globalAlignmentGraph(string a, string b) {
    int aLen = a.length() + 1;
    int bLen = b.length() + 1;
    int graph[aLen][bLen];
    for (int i = 0; i < aLen; i++) {
        for (int j = 0; j < bLen; j++) {
            if (i == 0 || j == 0) 
                graph[i][j] = 0;
            else {
                int diag = graph[i - 1][j - 1];
                int up = graph[i - 1][j];
                int left = graph[i][j - 1];
                if (a[i - 1] == b[j - 1])
                    graph[i][j] = diag + 1;
                else {
                    graph[i][j] = max(left, up);
                }
    }
        }
    }
    string longest = "";
    int i = aLen - 1;
    int j = bLen - 1;
    while (i > 0 && j > 0) {
            int up = graph[i - 1][j];
            int left = graph[i][j - 1];
        if (a[i - 1] == b[j - 1]) {
                longest.insert(0, charToString(a[i - 1]));
            i--;
            j--;
        }
        else {
                if (up > left)
                    i--;
            else
                j--;
            }
        }
    cout << longest << endl;
}



int main(int argc, const char * argv[]) {
    string a = "AGTGATGGCCATTTTAGGTAACCAGCACCGAAAGTCTGTGTAATGGGGGTTGCGGGTGTGTACACAGAGAACGCTGTGACCAGTCGGTGCACTGGATACACTCGACGAGGTCAGGTCTCAATTACGTACCAACAACCAAGCACCTTCCATCATGCTAAACGCGGCGCCCTGGCCAGTGAGTAGGAAGTAGTCCAAATTAGTATTCCATCGAACGTGCTGGAGTAGAGACAATTTCCTTCAGGCGTCCTCCGGTTTTCGGTCCGAAAGCCAGGGTGCGGCAAGTCAGTAATTCTAGAATGCCCCGATAGCGATGTTGCCCGTGCACAAGTATCCCTATGTTGCGGGGTCCGCTTTTACTCACCTAATGCGCAATACACTCACCGAATCGAGCGGTCATCTTACGGGAGGCCTGGACATGTCCTGTTCAGATTAACCCCCCCCGTCTGAGTTAACGATCGTATACAGTGAAATAAAACTATGCCAAGGCGCCGGAGTCATGTATGAATAGCTATTAGCATGTCATCAGATCTCCCCGCGCGCGACAAACGCGTCGCATGCCAATTTCACTCCGTTCGCAGGCGGTTTTGCGGGGCGGTCCGCGTCACTTATTGGGGCTTGTCCAGTGATCCTTCCAAGGCATCCTGGCTCAATAAGTTTGTCAGCAACCAGAGAATTTCAAGACTCGAAGCGGTAATGTGCCTTGCAGCTTAGACTTTACTCGGTAGGAAGTAGTAAGGACATCGGACTTTCTCACGCGTCCAGTCGACACACTACCATAGCCAAGCTCAAACACGACACTAGTTAACACTAGATACATCTACCAACAAGTCCAACTAAATTCAGGTTGGTCTCCCCCAGCGTGGCGTGCTTACCGCTCGATATGAGGGCTTAAGCGTAATCCATGTTCCCGCTGGTCTTGTTTACCCGC";
    string b = "AAGCACGCGCCTGACTTTACGCCATGCTTAGTTTATCTGCGTTACTAACGACGTTATCTTTATACTGGCCAGCTACCTTAATGATCAATCCCGGACGTGAGAAGTGGCCTGTTATTGCAATGCAGATGTCGTAAGAAACATGTTAGGCGATAATCTAACCTCGAGTCGCAGTCTCCTTGTCGAGCGCACACTGGCTTCCGGCAGTGGTCAGGAAATACCACACAGTGAGGACGCGATCCCCGATGGTCGATTAGAGTGAGAACCCATCAAGGGAGTGCTATGAAGTATTCTTATATCCGTGGCTAAAGCACTGAATACGCTGCAATACAGTACCAACCAAGAAGGGATCCAGGAGCTCTGCTCAACAAATACTCGGAATGTACACTTTATGCCGCCTGTGCATACGGTTTCCGGTAATTGGAAGTGTGCTCACGGACCTGTCTGAGCCTATGGGCCGTAGGCAATATGCAAGAGCATGGTTCTCTGGCTCGCGTACGTCATTAGAGAAATCGATTGAAAAATTTTCGGTCGATCGATTCAGTTATTCCGACTGATTCGTCGACAAGATTCTCAGTAGCAATCTCATCTGGAGGTAGGTAGCCAACCCTCTCATTGCAAGATTGCCCTCGCGCCAACCTGGAACCCGTTACTCAGTGTGAATATACAAGAGAGTGGACTTGAGTTCTAGGGGTGCTTTACCATTCAAGAATTGGATAGTATCTGATGAACCAGTGCTCGTACAACATTCTCCCGTTGTTGATTGCGGAGAACTCAGCGCCTCTAAACGTATTTCTGTGAATTCATCGGTTCATGTGGCCCGAAGCCCTTTGATGGTCTTGCTTCGCTTTTCCGACCCAGGCGAACGAAAGGTCCATGCATTACTAAACCCGATGATGTATTTTAGT";
    globalAlignmentGraph(a, b);
    return 0;
}